version: '3.7'

services:
  postgres: 
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    restart: on-failure
    environment: 
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    ports: 
    - 5432:5432
    networks:
      backend:
        ipv4_address: 10.5.0.3

  project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project
    restart: always
    volumes: 
    - ./:/app
    - /app/node_modules
    - /app/.next
    ports: 
    - 3000:3000
    networks:
      backend:
        ipv4_address: 10.5.0.2
    command: ["./start.sh"]

networks:
  backend:
    driver: bridge
    ipam: 
      config: 
      - subnet: 10.5.0.0/16
        gateway: 10.5.0.1 